apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
          image: nsharc4/frontend-optixchange:latest
          ports:
            - containerPort: 3000
      volumes:
        - name: env-volume
          configMap:
            name: frontend-config
