apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_HOST: ZGItY2FjaGluZy1ibHIxLTQ3NDg4LWRvLXVzZXItNzQ3MzIxMy0wLmYuZGIub25kaWdpdGFsb2NlYW4uY29t
  REDIS_PORT: MjUwNjE=
  REDIS_PASSWORD: QVZOU19GeWM5VWJmeTVOd25ES1luS0It
